### PR TITLE
updating docs

### PR DESCRIPTION
**Pull request by rajarshi15220**

### CODE REVIEW

**Comment by hlovdal** [comment]
I suspect this pull request to be motivated by Hacktober participation.

**Comment by rajarshi15220** [comment]
yes, it is,
if you approve it helps me.
Thankyou

**Comment by cyberhck** [comment]
Here's my 2 cents, this PR is not adding any value to the project, this is not the spirit of hacktoberfest, please either create a more meaningful PR (changing from specified to very specified isn't good), to the maintainer, hacktoberfest clearly says you should put "invalid" or "spam" if you find this kind of PRs which will help them give a fair and good experience to everyone.

**Comment by alhardy** [comment]
The only change is see is add very to "very specified interval" which doesn't really make sense

**Pull request closed without merging**
