### PR TITLE
Add bucketed histograms and timers

### PR DESCRIPTION
**Pull request by mikenorgate**
### The issue or feature being addressed

This is a start on the new metric required for AppMetrics/AppMetrics#278 (New metric type for Prometheus histograms)

### Details on the issue fix or feature implementation

I have created a new BucketHistogram which allows the end user to decide which buckets they would like and then keeps a count for each bucket.

The bucket to increment is based on finding the largest bucket that is <= to the value

### Confirm the following

- [X] I have ensured that I have merged the latest changes from the dev branch
- [X] I have successfully run a [local build](https://github.com/AppMetrics/AppMetrics#how-to-build)
- [X] I have included unit tests for the issue/feature
- [X] I have included the github issue number in my commits

### CODE REVIEW

**Comment by saxus** [comment]
Hi!. Any news with this pull request?

**Comment by alhardy** [comment]
@saxus sorry not yet, still need to find some time to take a look.

**Comment by megakid** [comment]
We have just started our migration to Prometheus and would love this feature set also.

**Comment by alhardy** [comment]
@mikenorgate could you resolve the conflicts?

**Comment by mikenorgate** [comment]
What have I got wrong that is causing the build failures?

**Comment by pierrediancourt** [comment]
That would be really useful to me too.
It looks like this feature has been forgotten, isn't it?

**Comment by alhardy** [comment]
There were conflicts and build was failing, I didn't have a chance to look into it at the time. Theres a fair bit to review and wrap my head around the bucketed metric concepts. Will look into if several find this useful for prom

**Comment by martin-kromkamp-cko** [comment]
Is there any progress on this feature?

So far the only thing that makes me reach for the prometheus-net library every now and then is the lack of Prometheus histograms in this library. I would love to be able to stick to one library. 🙂

**Comment by alhardy** [comment]
@martin-kromkamp-cko I haven't had a chance to look into this yet. Since you're in need of this feature, would you be able to help out getting the merge conflicts and build working for the PR?

**Comment by martin-kromkamp-cko** [comment]
@alhardy I should be able to take a loot at that. Just noticed @mikenorgate merged dev into his upstream branch as well, does this mean you are able to get a bit of time at hand to see if we can get the builds to pass? I have a Windows and Linux machine here so should can help out with the failing Linux build 👍 

My first question would be if you want to have this PR continuing against the dev branch or if it should be pulled into the next release branch (4.2.0 I think)?

**Comment by alhardy** [comment]
Yep I can help with the build if you can't get it working, and yep work on the 4.2 branch please

**Comment by mikenorgate** [comment]
I'm just taking a look a the build, it seems my tests are currently failing due to a serialisation issue with the change to `System.Text.Json`. I'm just trying to resolve it now

**Comment by mikenorgate** [comment]
I think I've resolved the issues and the build is now passing

**Comment by alhardy** [comment]
Nice. Ill give the code a run and test sometime next week.

**Comment by efmk** [comment]
New bucket timer metrics has duration unit in milliseconds by default. But prometheus expects that buckets are in seconds.
Due to this fact, there is no possibility to properly build _histogram_quantile_ function in grafana.
Consider to add some configuration for duration unit of RequestTransactionDuration and EndpointRequestTransactionDuration metrics.

**Pull request merged**
