### PR TITLE
Fix #314 ResetOnReporting does nothing

### LINKED ISSUE #314: ResetOnReporting does nothing
When defining a counter you can set CounterOptions property 'ResetOnReporting' to true like this:

```
            public static CounterOptions ReceivedMessages => new CounterOptions
            {
                Context = ContextName,
                Name = "Fetching",
                MeasurementUnit = Unit.Items,
                ResetOnReporting = true
            };
```

However, when the metrics are flushed, the counters are not reset, and will be cumulative with the next set of values.

You can force a reset when you configure an 'AppMetricsTaskScheduler', but in doing so you are overriding this property and have to name the individual counters:

```
            var scheduler = new AppMetricsTaskScheduler(
                TimeSpan.FromSeconds(5),
                async () =>
                {
                    await Task.WhenAll(((IMetricsRoot) metrics).ReportRunner.RunAllAsync());
                    metrics.Provider.Counter.Instance(MetricsRegistry.MyMetrics.ReceivedMessages).Reset();
                });
            scheduler.Start();
```

How should the 'ResetOnReporting' actually be used??

### PR DESCRIPTION
**Pull request by mortengjesing**
### The issue or feature being addressed

- https://github.com/AppMetrics/AppMetrics/issues/314

### Details on the issue fix or feature implementation

- ToSerializableMetric now calls source.ValueProvider.GetValue(source.ResetOnReporting) instead of source.Value.Count that are not resetting the count.

- Changed the IMetricValueProvider in the Counter unit test from ConstantValueProvider to DefaultCounterMetric as ConstantValueProvider has not implemented the GetValue with resetMetrics correct.

### Confirm the following

- [x] I have ensured that I have merged the latest changes from the dev branch
- [x] I have successfully run a [local build](https://github.com/alhardy/AppMetrics#how-to-build)
- [x] I have included unit tests for the issue/feature
- [x] I have included the github issue number in my commits

### CODE REVIEW

**Comment by mortengjesing** [comment]
Hi @alhardy, when do you plan to release the fix?

**Comment by alhardy** [comment]
@Maximusya yes, I'll release an pre-release sometime this week

**Comment by mts57017** [comment]
i need this change as well, thanks!

**Comment by mortengjesing** [comment]
@alhardy is there some way I can help getting this released?

**Pull request merged**
