### PR TITLE
Added fix for arithmetic overflow at DefaultAlgorithmRReservoir

### PR DESCRIPTION
**Pull request by AxelUser**
Thanks for helping out :+1:

Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/main/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`

### Details on the issue fix or feature implementation
Original method from DefaultAlgorithmRReservoir has a bug with arithmetic overflow. It was caused by casting total count of type long to int.
When reservoir processed more than int.MaxValue elements, this unchecked cast will result in negative value of a size.
During snapshot creation array of UserValueWrappers will be created with negative size, thus resulting into OverflowException.
Now during casting total count to int it will be always lower than int.MaxValue, because it is compared to value's size.

### Confirm the following

- [x] I have ensured that I have merged the latest changes from the dev branch
- [x] I have successfully run a [local build](https://github.com/AppMetrics/AppMetrics#how-to-build)
- [ ] I have included unit tests for the issue/feature
- [ ] I have included the github issue number in my commits

### CODE REVIEW

**Comment by AxelUser** [comment]
Hi @alhardy!

May you have a look on these fixes, please?

**Comment by alhardy** [comment]
Sure, will be after Xmas though

**Comment by AxelUser** [comment]
Hi, @alhardy !

Merry Christmas and happy new year! May you have a look on this PR, please?

**Comment by alhardy** [comment]
> Hi, @alhardy !
> 
> Merry Christmas and happy new year! May you have a look on this PR, please?

Thanks, same to you.

Ill have a look sometime this week

**Comment by alhardy** [comment]
@AxelUser LGTM

Could you please create the PR against the feature/4.2.0 branch instead of the dev branch though

Cheers

**Comment by AxelUser** [comment]
Done!

**Review by alhardy — APPROVED** [review]

**Pull request merged**
