### PR TITLE
Add product version in /end endpoint to fix #267

### LINKED ISSUE #267: Customisable properties in /env
Hi,

Would it be possible to display the productversion in the /env endpoint?

https://github.com/AppMetrics/AppMetrics/blob/8793a239c907a25e1c0085e8ebb61204c63e82e6/src/App.Metrics.Core/Infrastructure/EnvironmentInfoProviderCache.cs#L42

Adding 
```FileVersionInfo.GetVersionInfo(Assembly.GetEntryAssembly().Location).ProductVersion```
should work

Currently, you only display the file version, but with dotnet command line, it is very convenient to set a version suffix, thus it make sense to display that info.
See --version-suffix here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore2x#options

Thank you

### PR DESCRIPTION
**Pull request by tomap**
### The issue or feature being addressed

- #267

### Details on the issue fix or feature implementation

- I just based my implementation on what was already done for assembly version

### Confirm the following

- [X ] I have ensured that I have merged the latest changes from the dev branch
- [ X] I have successfully run a [local build](https://github.com/alhardy/AppMetrics#how-to-build)
- [x] I have included unit tests for the issue/feature 
  - I need help on that one
- [ X] I have included the github issue number in my commits

### CODE REVIEW

**Comment by alhardy** [comment]
Build looks fine. Not sure if you saw my previous comment Thinking we can make what's provided in the environment info extensible from client apps instead. Thoughts?

**Comment by tomap** [comment]
Hi,

Yes, making /env extensible would be nice
- /env => a bunch of properties that don't change during the life of the program execution
- /health => a bunch of properties that do change during the life of the program execution

In fact, in my current implementation, I have created a health check that collects all version numbers of all assemblies installed in my program path...

I was looking for a way to move it to /env but saw that there was no extension point.

I'm not sure it's worth the effort: I mean, I would understand if you wanted to keep /env as simple as it is, but the product version would be nice, in the meantime.

Maybe we could open an issue and see how many votes it gets before starting to dev?

**Comment by bdrupieski** [comment]
As another consumer of this library I vote to make /env extensible so that if people want to add this they can. Not everyone needs or wants this information, but because of it they'll be required to have `System.Diagnostics.FileVersionInfo` as a dependency with this PR.

**Comment by tomap** [comment]
Then I agree, let's work on an extension point for /env
@alhardy & @bdrupieski do you have an idea on how to do it?/where to do it?

**Comment by alhardy** [comment]
Closing this one, review in issue https://github.com/AppMetrics/AppMetrics/issues/267

**Pull request closed without merging**
